# Generated by Django 2.2.5 on 2019-10-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0020_submission_verdict_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_generator_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polygon.Generator'),
        ),
    ]
