# Generated by Django 2.2.5 on 2019-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0026_auto_20191015_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='example_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
