# Generated by Django 2.2.5 on 2019-10-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0027_auto_20191016_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='testing_message',
            field=models.CharField(blank=True, default='Testing', max_length=128),
        ),
    ]
