# Generated by Django 2.2.5 on 2019-10-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0028_submission_testing_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('CPP17', 'gcc C++ 17')], max_length=64),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WA', 'Wrong answer'), ('PE', 'Presentation error'), ('EOF', 'UNEXPECTED_EOF'), ('TLE', 'Time limit exceeded'), ('MLE', 'Memory limit exceeded'), ('RE', 'Runtime error'), ('CP', 'Compilation Error'), ('TE', 'Test error'), ('UC', 'Unknown code')], default=None, max_length=64, null=True),
        ),
    ]
