# Generated by Django 2.2.5 on 2019-10-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0030_auto_20191018_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
