# Generated by Django 2.2.5 on 2019-10-19 14:24

from django.db import migrations, models
import django.db.models.deletion
import polygon.models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0031_submission_in_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=polygon.models.get_problem_file_folder)),
                ('problem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polygon.Problem')),
            ],
        ),
    ]
