# Generated by Django 2.2.5 on 2019-10-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0032_problemfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='input_format',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statement',
            name='legend',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statement',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statement',
            name='output_format',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='statement',
            name='problem_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
