# Generated by Django 2.2.5 on 2019-10-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0033_auto_20191019_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statement',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
