# Generated by Django 2.2.5 on 2019-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0035_auto_20191019_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('CPP17', 'gcc C++ 17'), ('PYTHON3.7', 'python 3.7')], max_length=64),
        ),
    ]
