# Generated by Django 2.2.5 on 2019-10-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0037_problem_interactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='example_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
