# Generated by Django 2.2.5 on 2019-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0039_auto_20191027_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='generator_compiled',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='checker_compiled',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='interactor_compiled',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_compiled',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
