# Generated by Django 2.2.5 on 2019-10-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0040_auto_20191027_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTestGroupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.Problem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.Submission')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.TestGroup')),
            ],
        ),
        migrations.AddField(
            model_name='submissiontestresult',
            name='test_group_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polygon.SubmissionTestGroupResult'),
        ),
    ]
