# Generated by Django 2.2.5 on 2019-10-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0041_auto_20191029_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='testing_message',
            field=models.CharField(blank=True, default='Testing', max_length=256),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict_debug_message',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict_message',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='submissiontestresult',
            name='verdict_debug_message',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='submissiontestresult',
            name='verdict_message',
            field=models.CharField(default='', max_length=256),
        ),
    ]
