version: '3'

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PRODUCTION_ENV=1
      - CELERY_BROKER=redis://:yourpassword@redis:6379
      - CELERY_BACKEND=redis://:yourpassword@redis:6379
#    volumes:
#      - /var/www/tau.moe/media:/code/media # media files
#      - /var/www/tau.moe/production_static:/code/production_static # media files
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A arrow worker -l info -n celery-host-wroker@%h
    environment:
      - PRODUCTION_ENV=1
      - CELERY_BROKER=redis://:yourpassword@redis:6379
      - CELERY_BACKEND=redis://:yourpassword@redis:6379
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-judge:
    build:
      context: .
      dockerfile: Dockerfile_worker
    command: celery -A arrow worker -l info -Q sandbox_execution --concurrency=1 -n celery-judge-wroker@%h
    privileged: true
    cap_add:
      - ALL
    environment:
      - PRODUCTION_ENV=1
      - CELERY_BROKER=redis://:yourpassword@redis:6379
      - CELERY_BACKEND=redis://:yourpassword@redis:6379
    depends_on:
      - db
      - redis
      - web
      - celery
  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://:yourpassword@redis:6379", "--port=8888"]
    ports:
      - 8888:8888
    depends_on:
      - db
      - redis

volumes:
  db-data: