############################################################
# Dockerfile to build sandbox for executing user code
############################################################

FROM ubuntu:18.04
# FROM alpine:3.7
USER root

# Update the repository sources list
# RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list
RUN apt update -y
RUN apt upgrade -y
RUN apt update -y
RUN apt install -y bash
#install all the languages/compilers we are supporting.
RUN apt install -y g++
RUN apt install -y python
RUN apt install -y python3
RUN apt install -y python3-pip
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt install -y python3.7
RUN python3.7 -m pip install pip

RUN apt install -y coreutils
ENV PATH="/bin:${PATH}"
RUN apt install -y bc
RUN apt install -y make
RUN apt install -y libcap-dev
RUN apt install -y libpq-dev python-dev


RUN apt -y install libz-dev libjpeg-dev libfreetype6-dev python-dev

# user for sandbox scripts
RUN useradd -ms /bin/bash dummy

COPY polygon/isolate /isolate
RUN sh /isolate/install.sh
# RUN echo "mysql ALL = NOPASSWD: /usr/sbin/service mysql start" | cat >> /etc/sudoers
RUN echo "export PATH=$PATH" > /etc/environment

COPY . /app/

WORKDIR /app

# Run install.sh
RUN sh /app/worker_setup/install.sh

# Run container
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV C_FORCE_ROOT="true"

CMD sh /app/run_worker.sh
