# Generated by Django 2.2.5 on 2019-11-02 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polygon', '0044_auto_20191101_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_ioi_style', models.BooleanField(default=False, max_length=256)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=7200)),
                ('is_started', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('manual_control', models.BooleanField(default=False)),
                ('is_launched', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.Contest')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polygon.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContestUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestUserTaskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.FloatField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('tries', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.Contest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.ContestTask')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.ContestUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ContestUserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.Contest')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.Submission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.ContestTask')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.ContestUserProfile')),
                ('user_task_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contester.ContestUserTaskProfile')),
            ],
        ),
    ]
