# Generated by Django 2.2.5 on 2019-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contester', '0002_auto_20191102_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuserprofile',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contestuserprofile',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contestuserprofile',
            name='points_after_contest',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contestuserprofile',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestuserprofile',
            name='solved_count_after_contest',
            field=models.IntegerField(default=0),
        ),
    ]
