# Generated by Django 2.2.5 on 2019-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contester', '0003_auto_20191102_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestusersubmission',
            name='upsolving',
            field=models.BooleanField(default=False),
        ),
    ]
