# Generated by Django 2.2.5 on 2019-10-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_problemset_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='problemset_profile',
        ),
    ]
