# Generated by Django 2.2.5 on 2019-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0003_auto_20191015_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsetUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tasks_solved', models.ManyToManyField(to='problemset.ProblemsetTask')),
            ],
        ),
    ]
