from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='contester.views.index'),
    path('my_contests/', views.my_contests, name='contester.views.my_contests'),
    path('contest/<int:contest_id>/register/', views.register_to_contest,
         name='contester.views.register_to_contest'),
    path('contest/<int:contest_id>/', views.view_contest_tasks,
         name='contester.views.view_contest'),
    path('contest/<int:contest_id>/summary/', views.view_user_profile_summary,
         name='contester.views.view_user_profile_summary'),
    path('contest/<int:contest_id>/task/<int:pk>/', views.view_contest_task,
         name='contester.views.view_contest_task'),
    path('contest/<int:contest_id>/submission/<int:pk>/', views.submission,
         name='contester.views.view_submission'),
    path('contest/<int:contest_id>/my_submissions/', views.my_submissions,
         name='contester.views.my_submissions'),
    path('contest/<int:contest_id>/submissions/', views.contest_submissions,
         name='contester.views.contest_submissions'),
    path('contest/<int:contest_id>/standings/', views.contest_standings,
         name='contester.views.contest_standings'),

    # Manage Contest
    path('manage/contest/', views.manage_contests,
         name='contester.views.manage_contests'),
    path('manage/contest/create/', views.create_contest,
         name='contester.views.create_contest', ),
    path('manage/contest/<int:pk>/manage/', views.manage_contest,
         name='contester.views.manage_contest', ),
    path('manage/contest/<int:pk>/delete/', views.delete_contest,
         name='contester.views.delete_contest', ),
    path('manage/contest/<int:pk>/danger/', views.contest_danger_zone,
         name='contester.views.contest_danger_zone', ),
    # Manage Contest Registered Users
    path('manage/contest/<int:pk>/user/manage/', views.manage_registered_users,
         name='contester.views.manage_registered_users', ),
    path('manage/contest/<int:pk>/user/invite/', views.invite_user_to_contest,
         name='contester.views.invite_user_to_contest', ),
    path('manage/contest/<int:contest_id>/user/<int:pk>/delete/',
         views.delete_registered_user,
         name='contester.views.delete_registered_user', ),

    # Contest Control Panel
    path('manage/contest/<int:pk>/panel/', views.contest_control_panel,
         name='contester.views.contest_control_panel', ),
    path('manage/contest/<int:pk>/panel/launch/', views.launch_contest,
         name='contester.views.launch_contest', ),
    path('manage/contest/<int:pk>/panel/abort/', views.abort_contest,
         name='contester.views.abort_contest', ),
    path('manage/contest/<int:pk>/panel/start/', views.start_contest,
         name='contester.views.start_contest', ),
    path('manage/contest/<int:pk>/panel/stop/', views.stop_contest,
         name='contester.views.stop_contest', ),
    # Manage Contest Task
    path('manage/contest/<int:pk>/task/', views.manage_contest_tasks,
         name='contester.views.manage_contest_tasks'),
    path('manage/contest/<int:pk>/task/reorder/', views.reorder_tasks,
         name='contester.views.reorder_tasks'),
    path('manage/contest/<int:pk>/task/add/', views.add_contest_task,
         name='contester.views.add_contest_task'),
    path('manage/contest/<int:contest_id>/task/<int:pk>/',
         views.manage_contest_task,
         name='contester.views.manage_contest_task'),
    path('manage/contest/<int:contest_id>/task/<int:pk>/delete/',
         views.delete_contest_task,
         name='contester.views.delete_contest_task'),
]
