# Generated by Django 2.2.5 on 2019-10-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0004_statement_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('generator', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='test',
            old_name='example',
            new_name='is_example',
        ),
        migrations.AlterField(
            model_name='test',
            name='generator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polygon.Generator'),
        ),
    ]
