# Generated by Django 2.2.5 on 2019-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0006_auto_20191007_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
