# Generated by Django 2.2.5 on 2019-10-08 10:40

from django.db import migrations, models
import polygon.models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0008_auto_20191008_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='legend',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='output_format',
        ),
        migrations.AddField(
            model_name='statement',
            name='pdf_statement',
            field=models.FileField(blank=True, upload_to=polygon.models.get_statement_folder),
        ),
    ]
