# Generated by Django 2.2.5 on 2019-10-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0010_statement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='generator',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polygon.Problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='use_generator',
            field=models.BooleanField(default=False),
        ),
    ]
