# Generated by Django 2.2.5 on 2019-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0011_auto_20191011_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
