# Generated by Django 2.2.5 on 2019-10-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0012_worker_is_busy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Executor',
        ),
    ]
