# Generated by Django 2.2.5 on 2019-10-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0015_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_interactive',
            field=models.BooleanField(default=False),
        ),
    ]
