# Generated by Django 2.2.5 on 2019-10-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0017_auto_20191013_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='message',
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WA', 'Wrong answer'), ('PE', 'Presentation error'), ('EOF', 'UNEXPECTED_EOF'), ('TLE', 'Time limit exceeded'), ('MLE', 'Memory limit exceeded'), ('RE', 'Runtime error'), ('TE', 'Test error'), ('UC', 'Unknown code')], max_length=64),
        ),
    ]
