# Generated by Django 2.2.5 on 2019-10-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0019_auto_20191014_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verdict_message',
            field=models.CharField(default='', max_length=64),
        ),
    ]
