# Generated by Django 2.2.5 on 2019-10-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0021_auto_20191014_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executor',
        ),
    ]
