# Generated by Django 2.2.5 on 2019-10-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0022_delete_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='is_ready',
            new_name='is_active',
        ),
    ]
