# Generated by Django 2.2.5 on 2019-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0024_test_example_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WA', 'Wrong answer'), ('PE', 'Presentation error'), ('EOF', 'UNEXPECTED_EOF'), ('TLE', 'Time limit exceeded'), ('MLE', 'Memory limit exceeded'), ('RE', 'Runtime error'), ('TE', 'Test error'), ('UC', 'Unknown code')], default=None, max_length=64, null=True),
        ),
    ]
