# Generated by Django 2.2.5 on 2019-10-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0025_auto_20191015_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='verdict_debug_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict_debug_message',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WA', 'Wrong answer'), ('PE', 'Presentation error'), ('EOF', 'UNEXPECTED_EOF'), ('TLE', 'Time limit exceeded'), ('MLE', 'Memory limit exceeded'), ('RE', 'Runtime error'), ('CP', 'CP'), ('TE', 'Test error'), ('UC', 'Unknown code')], default=None, max_length=64, null=True),
        ),
    ]
