# Generated by Django 2.2.5 on 2019-10-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0007_auto_20191015_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsetuserprofile',
            name='tasks_solved',
        ),
        migrations.RemoveField(
            model_name='problemsetuserprofile',
            name='tasks_tried',
        ),
        migrations.CreateModel(
            name='ProblemsetUserTaskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tried_count', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('problemset_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problemset.ProblemsetTask')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problemset.ProblemsetUserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='problemsetsubmission',
            name='user_task_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problemset.ProblemsetUserTaskProfile'),
            preserve_default=False,
        ),
    ]
