# Generated by Django 2.2.5 on 2019-10-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0008_auto_20191019_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsetsubmission',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problemset.ProblemsetUserProfile'),
        ),
    ]
