# Generated by Django 2.2.5 on 2019-10-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0010_auto_20191019_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsetusertaskprofile',
            name='problemset_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problemset.ProblemsetTask'),
        ),
        migrations.AlterField(
            model_name='problemsetusertaskprofile',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problemset.ProblemsetUserProfile'),
        ),
    ]
