# Generated by Django 2.2.5 on 2019-10-15 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problemset', '0004_problemsetuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsetuserprofile',
            name='tasks_tried',
            field=models.ManyToManyField(related_name='tasks_tried', to='problemset.ProblemsetTask'),
        ),
        migrations.AddField(
            model_name='problemsetuserprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
