# Generated by Django 2.2.5 on 2019-10-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_auto_20191015_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsetsubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='problemsetsubmission',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problemset.ProblemsetUserProfile'),
            preserve_default=False,
        ),
    ]
