# Generated by Django 2.2.5 on 2019-10-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsettask',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
