# Generated by Django 2.2.5 on 2019-10-31 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polygon', '0043_auto_20191030_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_ioi_style', models.BooleanField(max_length=256)),
                ('start_date_time', models.DateTimeField(default=None, null=True)),
                ('duration', models.IntegerField(default=7200)),
                ('is_started', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('manual_control', models.BooleanField(default=False)),
                ('is_launched', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polygon.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='ContestUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestUserTaskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('tries', models.IntegerField(default=0)),
                ('penalty', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('contest_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ContestUserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('contest_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestTask')),
                ('contest_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestUserProfile')),
                ('contest_user_task_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestUserTaskProfile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.Submission')),
            ],
        ),
    ]
