# Generated by Django 2.2.5 on 2019-11-01 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20191031_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
